version: '2'

services:
  postgres:
    image: postgres:9.5
    ports:
      - "9911:5432"
    privileged: true
    volumes:
      - "./dev_docker_data/psql:/var/lib/postgresql/data"
  redis:
    image: redis:3.2
    ports:
      - "9922:6379"
    command: redis-server --appendonly yes
    volumes:
      - "./dev_docker_data/redis:/data"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "9933:2181"
  kafka:
    image: wurstmeister/kafka:0.9.0.0
    ports:
      - "9944:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${MY_IP}
      KAFKA_ADVERTISED_PORT: 9940
      KAFKA_CREATE_TOPICS: "consumerApp1-gcm-c:1:1,consumerApp1-gcm-p:1:1,consumerApp2-gcm-c:1:1,consumerApp2-gcm-p:1:1,consumerApp3-gcm-c:1:1,consumerApp3-gcm-p:1:1,consumerApp4-gcm-c:1:1,consumerApp4-gcm-p:1:1,producerApp1-gcm-c:1:1,producerApp1-gcm-p:1:1,notifierApp1-gcm-c:1:1,notifierApp1-gcm-p:1:1,notifierApp2-gcm-c:1:1,notifierApp2-gcm-p:1:1,notifierApp3-gcm-c:1:1,notifierApp3-gcm-p:1:1,notifierApp4-gcm-c:1:1,notifierApp4-gcm-p:1:1,batchWorkerApp1-apns-c:1:1,batchWorkerApp1-apns-p:1:1,batchWorkerApp2-apns-c:1:1,batchWorkerApp2-apns-p:1:1,batchWorkerApp3-gcm-c:1:1,batchWorkerApp3-gcm-p:1:1,batchWorkerApp4-gcm-c:1:1,batchWorkerApp4-gcm-p:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    volumes:
      - "./dev_docker_data/kafka:/kafka"
