language: go

go:
  - 1.7

sudo: required

addons:
  postgresql: "9.5"

services:
  - postgres
  - docker

env:
  - LIBRDKAFKA_VERSION=0.9.2.x
  - LIBRDKAFKA_VERSION=master
  - FARM_URL=${FARM_URL}

cache:
  directories:
    - $HOME/.cache/librdkafka

before_install:
  - sudo /bin/bash ./travis.sh

sudo: false

before_script: make setup-ci

script: make test

after_success:
  - ./push_to_docker.sh
  - ./success_webhook.sh
