language: node_js

node_js:
  - 6.8.0

sudo: required

services:
  - docker

before_script:
  - make setup-global

script:
  - sudo service postgresql stop
  - make ci-test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  #- make cross
  #- ./push_to_docker.sh
  #- /bin/bash -c '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ] && curl -H POST $TEST_FARM_URL'
