# marathon
# https://github.com/topfreegames/marathon
# Licensed under the MIT license:
# http://www.opensource.org/licenses/mit-license
# Copyright © 2016 Top Free Games <backend@tfgco.com>

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "22224:2181"
  kafka:
    image: wurstmeister/kafka:0.10.1.0
    ports:
      - "22225:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${MY_IP}
      KAFKA_ADVERTISED_PORT: 22225
      KAFKA_CREATE_TOPICS: "consumerApp1-gcm-c:1:1,consumerApp1-gcm-p:1:1,consumerApp2-gcm-c:1:1,consumerApp2-gcm-p:1:1,consumerApp3-gcm-c:1:1,consumerApp3-gcm-p:1:1,consumerApp4-gcm-c:1:1,consumerApp4-gcm-p:1:1,producerApp1-gcm-c:1:1,producerApp1-gcm-p:1:1,notifierApp1-gcm-c:1:1,notifierApp1-gcm-p:1:1,notifierApp2-gcm-c:1:1,notifierApp2-gcm-p:1:1,notifierApp3-gcm-c:1:1,notifierApp3-gcm-p:1:1,notifierApp4-gcm-c:1:1,notifierApp4-gcm-p:1:1,batchWorkerApp1-apns-c:1:1,batchWorkerApp1-apns-p:1:1,batchWorkerApp2-apns-c:1:1,batchWorkerApp2-apns-p:1:1,batchWorkerApp3-gcm-c:1:1,batchWorkerApp3-gcm-p:1:1,batchWorkerApp4-gcm-c:1:1,batchWorkerApp4-gcm-p:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    volumes:
      - "/tmp/marathon/kafka:/kafka"
    links:
      - zookeeper
  zookeeper-aguia:
    image: wurstmeister/zookeeper
    ports:
      - "22226:2181"
  kafka-aguia:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - "22227:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${MY_IP}
      KAFKA_ADVERTISED_PORT: 22227
      KAFKA_CREATE_TOPICS: "consumerApp1-gcm-c:1:1,consumerApp1-gcm-p:1:1,consumerApp2-gcm-c:1:1,consumerApp2-gcm-p:1:1,consumerApp3-gcm-c:1:1,consumerApp3-gcm-p:1:1,consumerApp4-gcm-c:1:1,consumerApp4-gcm-p:1:1,producerApp1-gcm-c:1:1,producerApp1-gcm-p:1:1,notifierApp1-gcm-c:1:1,notifierApp1-gcm-p:1:1,notifierApp2-gcm-c:1:1,notifierApp2-gcm-p:1:1,notifierApp3-gcm-c:1:1,notifierApp3-gcm-p:1:1,notifierApp4-gcm-c:1:1,notifierApp4-gcm-p:1:1,batchWorkerApp1-apns-c:1:1,batchWorkerApp1-apns-p:1:1,batchWorkerApp2-apns-c:1:1,batchWorkerApp2-apns-p:1:1,batchWorkerApp3-gcm-c:1:1,batchWorkerApp3-gcm-p:1:1,batchWorkerApp4-gcm-c:1:1,batchWorkerApp4-gcm-p:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-aguia:2181"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    volumes:
      - "/tmp/marathon/kafka2:/kafka"
    links:
      - zookeeper
  postgres:
    image: postgres:9.6
    ports:
      - "22222:5432"
  redis:
    image: redis:3.2.4-alpine
    ports:
      - "22223:6379"
