# marathon
# https://github.com/topfreegames/marathon
# Licensed under the MIT license:
# http://www.opensource.org/licenses/mit-license
# Copyright © 2016 Top Free Games <backend@tfgco.com>

---
app:
  log:
    level: "LOG_LEVEL"
    logToStdOut: "LOG_STDOUT"
  services:
    redis:
      url: "REDIS_URL"
    postgresql:
      url: "PG_URL"
    kafka:
      api:
        client:
          url: "KAFKA_URL"
          clientId: "KAFKA_CLIENT_ID"
  port: "PORT"
