---
app:
  log:
    level: debug
    logToStdOut: true
    logToFile: false
    file: /tmp/marathon.log
  name: 'Marathon'
  services:
    redis:
      url: //localhost:22223
      db: 0
      password: ''
      shouldReconnect: true
    postgresql:
      url: postgresql://marathon@localhost:22222/marathon
      options:
        native: true
        ssl: false
    kafka:
      api:
        client:
          url: localhost:22224
          clientId: marathonApiProducer

  port: 9000
  trophyRange: 500
  matchmaking:
    timeout: 30
    timeoutDiffOffset: 2
