---
db:
  host: localhost
  port: 5432
  user: felipecavalcanti
  password: postgres
  poolSize: 20
  maxRetries: 3
  database: marathon
push:
  db:
    host: localhost
    port: 5432
    user: felipecavalcanti
    password: postgres
    poolSize: 20
    maxRetries: 3
    database: push
