---
db:
  host: localhost
  port: 5432
  user: marathon_user
  password: ""
  poolSize: 20
  maxRetries: 3
  database: marathon
push:
  db:
    host: localhost
    port: 5432
    user: marathon_user
    password: ""
    poolSize: 20
    maxRetries: 3
    database: push
