---
db:
  host: localhost
  port: 8585
  user: marathon_user
  password: ""
  poolSize: 20
  maxRetries: 3
  database: marathon
push:
  db:
    host: localhost
    port: 8558
    user: marathon_user
    password: ""
    poolSize: 20
    maxRetries: 3
    database: push
s3:
  bucket: "tfg-push-notifications"
  folder: "test/files"
  daysExpiry: 1
  accessKey: "ACCESS-KEY"
  secretAccessKey: "SECRET-ACCESS-KEY"
workers:
  statsPort: 8081
  concurrency: 10
  redis:
    server: localhost:6333
    database: 0
    poolSize: 10
