---
db:
  host: localhost
  port: 8585
  user: postgres
  pass: ""
  poolSize: 20
  maxRetries: 3
  database: marathon
push:
  db:
    host: localhost
    port: 8558
    user: marathon_user
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: push
s3:
  bucket: "tfg-push-notifications"
  region: "us-east-1"
  folder: "development/jobs"
  daysExpiry: 1
  accessKey: "ACCESS-KEY"
  secretAccessKey: "SECRET-ACCESS-KEY"
workers:
  statsPort: 8081
  createBatches:
    batchSize: 20000
    dbPageSize: 20000
    pageProcessingConcurrency: 20
    concurrency: 10
    maxRetries: 5
  createBatchesFromFilters:
    dbPageSize: 10000
    pageProcessingConcurrency: 10
    concurrency: 10
    maxRetries: 5
  processBatch:
    concurrency: 10
    maxBatchFailure: 0.05
    maxUserFailureInBatch: 0.05
  zookeeper:
    hosts:
      - localhost:2288
  redis:
    poolSize: 10
    host: localhost
    port: 6333
    db: 0
    pass:
  topicTemplate: "%s-%s-c"
  resume:
    concurrency: 10
    maxRetries: 5
