postgres:
  user: "postgres"
  dbname: "marathon_development"
  host: "localhost"
  port: 5432
  sslmode: "disable"
s3:
  bucket: "tfg-push-notifications"
  folder: "test/files"
  daysExpiry: 1
  accessKey: "ACCESS-KEY"
  secretAccessKey: "SECRET-ACCESS-KEY"
healthcheck:
  workingtext: "working"
workers:
  logger:
    level: "fatal"
  consumer:
    consumergroup: "integration-development-consumer-group"
    topics: [ "integration-development-input-topic" ]
    brokers: [ "localhost:3536" ]
  producer:
    brokers: [ "localhost:3536" ]
  modules:
    consumers: 1
    parsers: 1
    fetchers: 1
    builders: 1
    producers: 1
    kafkadonechansize: 1
    fetcherdonechansize: 1
    inputkafkachansize: 10
    inputchansize: 10
    kafkatoparserchansize: 10
    parsertofetcherchansize: 10
    fetchertobuilderchansize: 10
    buildertokafkachansize: 10
    buildertokafkadonechansize: 1
batch_pg_workers:
  logger:
    level: "fatal"
  producer:
    brokers: [ "localhost:3536" ]
  modules:
    producers: 1
    pgtokafkachansize: 10
