postgres:
  # host: "localhost"
  # port: 9910
  # password: ""
  user: "marathon"
  dbname: "marathon"
  sslmode: "disable"
redis:
  # host: localhost
  # port: 9920
  # password: ""
  db: 0
  maxPoolSize: 20
s3:
  # accessKey: "ACCESS-KEY"
  # secretAccessKey: "SECRET-ACCESS-KEY"
  bucket: "tfg-push-notifications"
  folder: "test/files"
  daysExpiry: 1
sentry:
  # url: ""
healthcheck:
  workingtext: "working"
workers:
  logger:
    level: "debug"
  consumer:
    # FIXME: We have to keep this in sync with aguia
    consumergroupTemplate: "push-%s-%s-staging-single-consumer-group"
    # FIXME: We have to keep this in sync with aguia
    # FIXME: WE SHOULD NOT HAVE UNDERSCORES HERE
    topicTemplate: "push-%s_%s-staging-single-consumer-topic"
    # brokers: [ "localhost:9940" ]
  producer:
    # brokers: [ "localhost:9940" ]
    # FIXME: WE SHOULD NOT HAVE UNDERSCORES HERE
    topicTemplate: "push-%s_%s-staging-single-producer-topic"
  modules:
    producers: 1
    batchpgworkers: 1
    parsers: 1
    fetchers: 1
    builders: 1
    producers: 1
    batchpgworkerstatusdonechan: 1
    batchpgworkerdonechan: 1
    pgtoparserchan: 10000
    parserdonechan: 1
    parsertofetcherchan: 1000
    fetcherdonechan: 1
    fetchertobuilderchan: 1000
    builderdonechan: 1
    buildertoproducerchan: 1000
    producerdonechan: 1
