---
app:
  log:
    level: error
    logToStdOut: false
    logToFile: false
  name: 'Marathon'
  services:
    redis:
      url: //localhost:22223
      db: 1
      password: ''
      shouldReconnect: false
    postgresql:
      url: postgresql://marathon_test@localhost:22222/marathon_test
      options:
        native: true
        ssl: false
        logging: false
  port: 5051
