---
db:
  host: localhost
  port: 8585
  user: marathon_test_user
  password: ""
  poolSize: 20
  maxRetries: 3
  database: marathon_test
faultyDb:
  host: localhost
  port: 8585
  user: marathon_test_user
  password: ""
  poolSize: 20
  maxRetries: 3
  database: marathon_tet
s3:
  bucket: "tfg-push-notifications"
  folder: "test/files"
  daysExpiry: 1
  accessKey: "ACCESS-KEY"
  secretAccessKey: "SECRET-ACCESS-KEY"
workers:
  statsPort: 8081
  concurrency: 10
  redis:
    server: localhost:6333
    database: 0
    poolSize: 10
  zookeeper:
    hosts:
      - localhost:9930
  topicTemplate: "%s-%s-c"
