---
db:
  host: localhost
  port: 8585
  user: marathon_test_user
  password: ""
  poolSize: 20
  maxRetries: 3
  database: marathon_test
faultyDb:
  host: localhost
  port: 8585
  user: marathon_test_user
  password: ""
  poolSize: 20
  maxRetries: 3
  database: marathon_tet
push:
  db:
    host: localhost
    port: 8585
    user: marathon_test_user
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: marathon_test
s3:
  bucket: "tfg-push-notifications"
  folder: "test/jobs"
  region: "us-east-1"
  daysExpiry: 1
  accessKey: "ACCESS-KEY"
  secretAccessKey: "SECRET-ACCESS-KEY"
workers:
  statsPort: 8081
  createBatches:
    batchSize: 10000
    dbPageSize: 10000
    pageProcessingConcurrency: 10
    concurrency: 10
    maxRetries: 5
  createBatchesFromFilters:
    dbPageSize: 2
    pageProcessingConcurrency: 2
    concurrency: 10
    maxRetries: 5
  processBatch:
    concurrency: 10
  redis:
    poolSize: 10
    host: localhost
    port: 6333
    db: 0
    pass: 
  zookeeper:
    hosts:
      - localhost:9930
  topicTemplate: "%s-%s-c"
