---
db:
  host: localhost
  port: 5432
  user: marathon_test_user
  password: ""
  poolSize: 20
  maxRetries: 3
  database: marathon_test
faultyDb:
  host: localhost
  port: 5432
  user: marathon_test_user
  password: ""
  poolSize: 20
  maxRetries: 3
  database: marathon_tet
