postgres:
  user: "marathon_test"
  dbname: "marathon_test"
  host: "localhost"
  port: 5432
  sslmode: "disable"
redis:
  host: localhost
  port: 6379
  db: 0
  password: ""
  maxPoolSize: 20
s3:
  bucket: "tfg-push-notifications"
  folder: "test/files"
  daysExpiry: 1
  accessKey: "ACCESS-KEY"
  secretAccessKey: "SECRET-ACCESS-KEY"
sentry:
  url:
healthcheck:
  workingtext: "working"
workers:
  logger:
    level: "fatal"
  consumer:
    consumergroup: "integration-test-consumer-group"
    # FIXME: WE SHOULD NOT HAVE UNDERSCORES HERE
    topicTemplate: "push-%s_%s-staging-single-consumer-topic"
    brokers: [ "localhost:3536" ]
  producer:
    brokers: [ "localhost:3536" ]
    # FIXME: WE SHOULD NOT HAVE UNDERSCORES HERE
    topicTemplate: "push-%s_%s-staging-single-consumer-topic"
  modules:
    producers: 1
    batchpgworkers: 1
    parsers: 1
    fetchers: 1
    builders: 1
    producers: 1
    batchpgworkerstatusdonechan: 1
    batchpgworkerdonechan: 1
    pgtoparserchan: 10000
    parserdonechan: 1
    parsertofetcherchan: 1000
    fetcherdonechan: 1
    fetchertobuilderchan: 1000
    builderdonechan: 1
    buildertoproducerchan: 1000
    producerdonechan: 1
