postgres:
  user: "marathon_test"
  dbname: "marathon_test"
  host: "localhost"
  port: 5432
  sslmode: "disable"
healthcheck:
  workingtext: "working"
workers:
  logger:
    level: "debug"
  consumer:
    consumergroup: "test-consumer-group"
    topics: [ "input-topic" ]
    brokers: [ "localhost:3536" ]
  producer:
    brokers: [ "localhost:3536" ]
  modules:
    consumers: 1
    parsers: 1
    fetchers: 1
    builders: 1
    producers: 1
    kafkadonechansize: 1
    fecherdonechansize: 1
    inputkafkachansize: 10
    inputchansize: 10
    kafkatoparserchansize: 10
    parsertofetcherchansize: 10
    fetchertobuilderchansize: 10
    buildertokafkachansize: 10
batch_pg_workers:
  logger:
    level: "debug"
  producer:
    brokers: [ "localhost:3536" ]
  modules:
    producers: 1
    pgtokafkachansize: 10
